# These are assembled from snippets of actions built by Jim Hester.
# You will need to customize this template; the r-lib actions repository
# is a great place to start to figure things out: https://github.com/r-lib/actions

# This action is based on the 'pkgdown' action:
# https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml

# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions

# More information at https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

# I'm adding a lot of comments because you will likely need to adapt this
# to your circumstances. I trust the comments will be helpful; I also trust
# that anyone who sees a mistatement/error will feel welcome to file an issue
# at: https://github.com/ijlyttle/projthis/issues

# This section is used to define the triggers for launching an action.
# Comment, or uncomment what you think might be useful in your situation,
# or write your own.
on:

  # runs whenever you push any Rmarkdown file
  push:
    paths:
      - "**.Rmd"

  # runs on a schedule using UTC - see https://en.wikipedia.org/wiki/Cron
  # schedule:
  #  - cron:  '30 02 * * *' # 02:30 UTC, every day

# name of the workflow to appear in actions portal,
# e.g. https://github.com/ijlyttle/projthis/actions?query=workflow%3AR-CMD-check
name: run-workflows

jobs:
  # name of the job
  run-workflows:
    # there are other OS options available,
    # but the package-caching is set up for `macOS-latest`
    runs-on: macOS-latest
    # set variables in your environment:
    # as this is GitHub, your token is available
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      # these steps are provided by Jim Hester - as he makes improvements,
      # you may wish to update these steps. Keep an eye on:
      #   https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rmarkdown")
          remotes::install_local(".")
        shell: Rscript {0}

      # rename and adapt this step to build your project
      - name: Build something
        # if you are running only R commands, this can be a convenient syntax
        run: |
          # you can run more than one workflow here (uncomment to activate)
          # rmarkdown::render_site("workflow")
        shell: Rscript {0}

      # rename and adapt this step to deploy your project
      - name: Deploy something
        # need to be careful with `git add -A` as you might be committing
        # files that you would prefer not to commit:
        #   https://twitter.com/JennyBryan/status/1319320033063923712
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "updated by Actions"  || echo "No changes to commit"
          git push  || echo "No changes to commit"
